namespace Galaxy.Api
{
	public enum GogServicesConnectionState
	{
		GOG_SERVICES_CONNECTION_STATE_UNDEFINED = 0,
		GOG_SERVICES_CONNECTION_STATE_CONNECTED = 1,
		GOG_SERVICES_CONNECTION_STATE_DISCONNECTED = 2,
		GOG_SERVICES_CONNECTION_STATE_AUTH_LOST = 3
	}
}
