namespace Galaxy.Api
{
	public enum LeaderboardDisplayType
	{
		LEADERBOARD_DISPLAY_TYPE_NONE = 0,
		LEADERBOARD_DISPLAY_TYPE_NUMBER = 1,
		LEADERBOARD_DISPLAY_TYPE_TIME_SECONDS = 2,
		LEADERBOARD_DISPLAY_TYPE_TIME_MILLISECONDS = 3
	}
}
