namespace Galaxy.Api
{
	public enum LobbyTopologyType
	{
		DEPRECATED_LOBBY_TOPOLOGY_TYPE_FCM_HOST_MIGRATION = 0,
		LOBBY_TOPOLOGY_TYPE_FCM = 1,
		LOBBY_TOPOLOGY_TYPE_STAR = 2,
		LOBBY_TOPOLOGY_TYPE_CONNECTIONLESS = 3,
		LOBBY_TOPOLOGY_TYPE_FCM_OWNERSHIP_TRANSITION = 4
	}
}
