namespace Galaxy.Api
{
	public enum LobbyEnterResult
	{
		LOBBY_ENTER_RESULT_SUCCESS = 0,
		LOBBY_ENTER_RESULT_LOBBY_DOES_NOT_EXIST = 1,
		LOBBY_ENTER_RESULT_LOBBY_IS_FULL = 2,
		LOBBY_ENTER_RESULT_ERROR = 3,
		LOBBY_ENTER_RESULT_CONNECTION_FAILURE = 4
	}
}
