namespace Galaxy.Api
{
	public enum LobbyComparisonType
	{
		LOBBY_COMPARISON_TYPE_EQUAL = 0,
		LOBBY_COMPARISON_TYPE_NOT_EQUAL = 1,
		LOBBY_COMPARISON_TYPE_GREATER = 2,
		LOBBY_COMPARISON_TYPE_GREATER_OR_EQUAL = 3,
		LOBBY_COMPARISON_TYPE_LOWER = 4,
		LOBBY_COMPARISON_TYPE_LOWER_OR_EQUAL = 5
	}
}
