namespace Galaxy.Api
{
	public enum OverlayState
	{
		OVERLAY_STATE_UNDEFINED = 0,
		OVERLAY_STATE_NOT_SUPPORTED = 1,
		OVERLAY_STATE_DISABLED = 2,
		OVERLAY_STATE_FAILED_TO_INITIALIZE = 3,
		OVERLAY_STATE_INITIALIZED = 4
	}
}
