namespace Galaxy.Api
{
	public enum SavegameType
	{
		SAVEGAME_TYPE_UNDEFINED = 0,
		SAVEGAME_TYPE_AUTO = 1,
		SAVEGAME_TYPE_QUICK = 2,
		SAVEGAME_TYPE_MANUAL = 3,
		SAVEGAME_TYPE_POINT_OF_NO_RETURN = 4,
		SAVEGAME_TYPE_ENDGAME_SAVE = 5,
		SAVEGAME_TYPE_CHECKPOINT = 6
	}
}
