namespace Sunshine.Metric
{
	public enum EffectType
	{
		NONE = 0,
		STAT_BONUS = 1,
		SKILL_BONUS = 2,
		SET_VARIABLE = 3,
		DAMAGE = 4,
		HEAL = 5,
		THC_ORB_MONEY = 6,
		THC_ORB_XP = 7,
		THC_CRIT_RANGE_EXPAND = 8,
		THC_RED_CHECK_FAILURE = 9,
		MALE_TARGET = 10,
		FEMALE_TARGET = 11,
		KIM_TARGET = 12,
		REOPEN_WHITE = 13,
		MOUTH_SLOT = 14,
		TOOLTIP = 15,
		MAX_LEARNING_CAP = 16,
		COMMUNISM_XP_BONUS = 17,
		SKILL_BONUS_WITHOUT_SHIRT = 18,
		SKILL_BONUS_WHEN_UNARMED = 19,
		PASSIVES_SUCCEED = 20,
		DRUGS_ARE_BAD_MKAY = 21,
		PASSIVE_TARGET_MODIFIER = 22,
		XP_REWARD = 23,
		LUA_COMMAND = 24,
		FIND_BETTER_ITEMS = 25,
		REPUTATION_BONUS = 26,
		MODIFY_CAMERA_MAX_ZOOM_LIMIT = 27
	}
}
