namespace Sunshine.Metric
{
	public enum SkillType
	{
		NONE = 0,
		LOGIC = 1,
		ENCYCLOPEDIA = 2,
		RHETORIC = 3,
		DRAMA = 4,
		CONCEPTUALIZATION = 5,
		VISUAL_CALCULUS = 6,
		VOLITION = 7,
		INLAND_EMPIRE = 8,
		EMPATHY = 9,
		AUTHORITY = 10,
		SUGGESTION = 11,
		ESPRIT_DE_CORPS = 12,
		PHYSICAL_INSTRUMENT = 13,
		ELECTROCHEMISTRY = 14,
		ENDURANCE = 15,
		CONVALESCENCE = 16,
		HALF_LIGHT = 17,
		PAIN_THRESHOLD = 18,
		SHIVERS = 19,
		HE_COORDINATION = 20,
		PERCEPTION = 21,
		HEARING = 22,
		SIGHT = 23,
		SMELL = 24,
		TASTE = 25,
		REACTION = 26,
		SAVOIR_FAIRE = 27,
		INTERFACING = 28,
		COMPOSURE = 29,
		ALT = 30
	}
}
