namespace LocalizationCustomSystem
{
	public static class TermsUtils
	{
		public const string SKILLS_SOURCE_PATH = "Lockits/English/GeneralLockitEnglish";

		public const string ABILITIES_SOURCE_PATH = "Lockits/English/GeneralLockitEnglish";

		public const string ARCHETYPES_SOURCE_PATH = "Lockits/English/GeneralLockitEnglish";

		public const string DIFFICULTY_SOURCE_PATH = "Lockits/English/GeneralLockitEnglish";

		public const string MESSAGES_SOURCE_PATH = "Lockits/English/GeneralLockitEnglish";

		public const string NEWSPAPERENDGAMES_SOURCE_PATH = "Lockits/English/GeneralLockitEnglish";

		public const string AREA_NAMES_SOURCE_PATH = "Lockits/English/GeneralLockitEnglish";

		public const string ITEMS_SOURCE_PATH = "Lockits/English/GeneralLockitEnglish";

		public const string TIPS_SOURCE_PATH = "Lockits/English/GeneralLockitEnglish";

		public const string THOUGHTS_SOURCE_PATH = "Lockits/English/GeneralLockitEnglish";

		public const string CONVERSATION_SOURCE_PATH = "Lockits/English/GeneralLockitEnglish";

		public const string BUTTONS_TEXTS_SOURCE_PATH = "Lockits/English/GeneralLockitEnglish";

		public const string REMAINING_SOURCE_PATH = "Lockits/English/GeneralLockitEnglish";

		public const string BUTTONS_IMAGES_SOURCE_PATH = "Lockits/English/ImagesLockitEnglish";

		public const string DIALOGUES_SOURCE_PATH = "Lockits/English/DialoguesLockitEnglish";

		public const string LANGUAGE_TERM = "LANGUAGE_NAME";

		public const string THC_SOLUTION_TERM = "Buttons/THC_BUTTON_SOLUTION_TEXT";

		public const string THC_PROBLEM_TERM = "Buttons/THC_BUTTON_PROBLEM_TEXT";

		public const string HEALTH_LOCALIZATION_TERM = "HEALTH";

		public const string MORALE_LOCALIZATION_TERM = "MORALE";

		public const string MAINMENU_CONTINUE_TERM = "MAIN_MENU_CONTINUE";

		public const string MAINMENU_NEW_TERM = "MAIN_MENU_NEW_GAME";

		public const string MAINMENU_SAVE_TERM = "MAIN_MENU_SAVE";

		public const string MAINMENU_LOAD_TERM = "MAIN_MENU_LOAD";

		public const string MAINMENU_OPTIONS_TERM = "MAIN_MENU_OPTIONS";

		public const string MAINMENU_PHOTOMODE_TERM = "MAIN_MENU_PHOTOMODE";

		public const string MAINMENU_COLLAGEMODE_TERM = "MAIN_MENU_COLLAGEMODE";

		public const string MAINMENU_QUIT_TO_MAIN_MENU_TERM = "MAIN_MENU_QUIT_TO_MENU";

		public const string MAINMENU_QUIT_TO_DESKTOP_TERM = "MAIN_MENU_QUIT_TO_DESKTOP";

		public const string MAINMENU_QUICK_SAVE_TERM = "F1_SCREEN_QUICKSAVE_TITLE";

		public const string THC_BONUNES_HEADER_TERM = "THC_THOUGHTS_BONUSES_HEADER";

		public const string INV_BONUSES_HEADER_TERM = "INVENTORY_ITEMS_BONUSES_HEADER";

		public const string THC_TOOLTIP_INFO_TERM = "THC_TOOLTIP_INFO";

		public const string THC_TOOLTIP_EXP_TERM = "THC_TOOLTIP_EXP";

		public const string THC_TOOLTIP_SKILL_PINTS = "THC_TOOLTIP_SKILL_POINTS";

		public const string THC_RESEARCH_TIME_TERM = "THC_TOOLTIP_RESEARCH_TIME";

		public const string THC_RESEARCH_TIME_REMAINING_TERM = "THC_TOOLTIP_RESEARCH_TIME_REMAINING";

		public const string THC_BREAKTHROUGH_IMMINENT_TERM = "THC_TOOLTIP_BREAKTHROUGH_IMMINENT";

		public const string THC_COST_TO_UNLOCK_TERM = "THC_TOOLTIP_COST_TO_UNLOCK";

		public const string THC_UNLOCKABLE_TERM = "THC_UNLOCKABLE";

		public const string CHARSHEET_CREATION_ABILITIES_TITLE_TERM = "CHARSHEET_CREATION_ABILITIES_TITLE";

		public const string CHARSHEET_CREATION_SKILLS_TITLE_TERM = "CHARSHEET_CREATION_SKILLS_TITLE";

		public const string CHARSHEET_CHARACTER_VIEW_TITLE_TERM = "CHARSHEET_CHARACTER_VIEW_TITLE";

		public const string WEEKDAY_HIDDEN_TERM = "WEEKDAY_HIDDEN";

		public const string WEEKDAY_NEW_INFO_TERM = "WEEKDAY_NEW_INFO";

		public const string TASK_FILLED_TERM = "TASK_FILLED";

		public const string TASK_RESOLVED_TERM = "TASK_RESOLVED";

		public const string TASK_FORFEITED_TERM = "TASK_FORFEITED";

		public const string OFFICER_PROFILE_TITLE_TERM = "OFFICER_PROFILE_TITLE";

		public const string OFFICER_PROFILE_MISSING_TITLE_TERM = "OFFICER_PROFILE_MISSING_TITLE";

		public const string OFFICER_PROFILE_APOCALYPSE_TERM = "OFFICER_PROFILE_APOCALYPSE";

		public const string OFFICER_PROFILE_ART_TERM = "OFFICER_PROFILE_ART";

		public const string OFFICER_PROFILE_BORING_TERM = "OFFICER_PROFILE_BORING";

		public const string OFFICER_PROFILE_SORRY_TERM = "OFFICER_PROFILE_SORRY";

		public const string OFFICER_PROFILE_SUPERSTAR_TERM = "OFFICER_PROFILE_SUPERSTAR";

		public const string OFFICER_PROFILE_COMMUNIST_TERM = "OFFICER_PROFILE_COMMUNIST";

		public const string OFFICER_PROFILE_NATIONHOOD_TERM = "OFFICER_PROFILE_NATIONHOOD";

		public const string OFFICER_PROFILE_LIBERAL_TERM = "OFFICER_PROFILE_LIBERAL";

		public const string OFFICER_PROFILE_MORALIST_TERM = "OFFICER_PROFILE_MORALIST";

		public const string OFFICER_PROFILE_COACH_TERM = "OFFICER_PROFILE_COACH";

		public const string OFFICER_PROFILE_DESTROYER_TERM = "OFFICER_PROFILE_DESTROYER";

		public const string OFFICER_PROFILE_GOODBAD_COP_TERM = "OFFICER_PROFILE_GOODBAD_COP";

		public const string OFFICER_PROFILE_HONOUR_TERM = "OFFICER_PROFILE_HONOUR";

		public const string OFFICER_PROFILE_DORK_TERM = "OFFICER_PROFILE_DORK";

		public const string OFFICER_PROFILE_KILLED_TERM = "OFFICER_PROFILE_KILLED";

		public const string OFFICER_PROFILE_SOLVED_TERM = "OFFICER_PROFILE_SOLVED";

		public const string OFFICER_PROFILE_YEARS_TERM = "OFFICER_PROFILE_YEARS";

		public const string INVENTORY_TOOLTIP_PAWN_ALL_TERM = "INVENTORY_TOOLTIP_PAWN_ALL";

		public const string INVENTORY_TOOLTIP_TOOLS_TERM = "INVENTORY_TOOLTIP_TOOLS";

		public const string INVENTORY_TOOLTIP_CLOTHING_TERM = "INVENTORY_TOOLTIP_CLOTHING";

		public const string INVENTORY_TOOLTIP_INTERACT_TERM = "INVENTORY_TOOLTIP_INTERACT";

		public const string INVENTORY_TOOLTIP_ITEMS_TERM = "INVENTORY_TOOLTIP_ITEMS";

		public const string INVENTORY_TOOLTIP_USES_LEFT_TERM = "INVENTORY_TOOLTIP_USES_LEFT";

		public const string INVENTORY_TOOLTIP_INTRODUCTION_TITLE_TERM = "INVENTORY_TOOLTIP_INTRODUCTION_TITLE";

		public const string INVENTORY_TOOLTIP_INTRODUCTION_DESCRIPTION_TERM = "INVENTORY_TOOLTIP_INTRODUCTION_DESCRIPTION";

		public const string INVENTORY_TOOLTIP_PRICE_TERM = "INVENTORY_TOOLTIP_PRICE";

		public const string INVENTORY_TOOLTIP_PAWN_FOR_TERM = "INVENTORY_TOOLTIP_PAWN_FOR";

		public const string NEWSPAPER_DEFAULT_TITLE_TERM = "NEWSPAPER_DEFAULT_TITLE";

		public const string NEWSPAPER_DEFAULT_OPENER_TERM = "NEWSPAPER_DEFAULT_OPENER";

		public const string CHARSHEET_TOOLTIP_LEVEL_UP_TITLE_REQ_TERM = "CHARSHEET_TOOLTIP_LEVEL_UP_TITLE_REQ";

		public const string CHARSHEET_TOOLTIP_LEVEL_UP_DESC_SKILL_CAP_TERM = "CHARSHEET_TOOLTIP_LEVEL_UP_DESC_SKILL_CAP";

		public const string CHARSHEET_TOOLTIP_LEVEL_UP_DESC_MAX_SEGM_TERM = "CHARSHEET_TOOLTIP_LEVEL_UP_DESC_MAX_SEGM";

		public const string CHARSHEET_TOOLTIP_LEVEL_UP_DESC_NO_POINTS_TERM = "CHARSHEET_TOOLTIP_LEVEL_UP_DESC_NO_POINTS";

		public const string CHARSHEET_TOOLTIP_LEVEL_UP_DESC_SKILL_AVAIL_TERM = "CHARSHEET_TOOLTIP_LEVEL_UP_DESC_SKILL_AVAIL";

		public const string CHARACTER_NAME_UNKNOWN_TERM = "CHARACTER_NAME_UNKNOWN";

		public const string CHARACTER_DETAILS_UNKNOWN_TERM = "CHARACTER_DETAILS_UNKNOWN";

		public const string LOAD_SAVE_DAY_TERM = "LOAD_SAVE_DAY_NAME";

		public const string EFFECT_THC_ORB_MONEY_TERM = "EFFECT_THC_ORB_MONEY";

		public const string EFFECT_THC_CRIT_RANGE_EXPAND_TERM = "EFFECT_THC_CRIT_RANGE_EXPAND";

		public const string EFFECT_THC_RED_CHECKS_FAIL_TERM = "EFFECT_THC_RED_CHECKS_FAIL";

		public const string EFFECT_FEMALE_WORD_TERM = "EFFECT_FEMALE_WORD";

		public const string EFFECT_MALE_WORD_TERM = "EFFECT_MALE_WORD";

		public const string EFFECT_TOWARDS_WORD_TERM = "EFFECT_TOWARDS_WORD";

		public const string EFFECT_ALL_WHITE_CHECKS_UNLOCKED_TERM = "EFFECT_ALL_WHITE_CHECKS_UNLOCKED";

		public const string EFFECT_STRANGE_EFFECT_TERM = "EFFECT_STRANGE_EFFECT";

		public const string EFFECT_MOUTH_SLOT_TERM = "EFFECT_MOUTH_SLOT";

		public const string EFFECT_COMMUNISM_XP_BONUS_TERM = "EFFECT_COMMUNISM_XP_BONUS";

		public const string EFFECT_DRUGS_ARE_BAD_MKAY_TERM = "EFFECT_DRUGS_ARE_BAD_MKAY";

		public const string EFFECT_FIND_BETTER_ITEMS_TERM = "EFFECT_FIND_BETTER_ITEMS";

		public const string EFFECT_MODIFIER_SUSPICIOUS_TERM = "EFFECT_MODIFIER_SUSPICIOUS";

		public const string TOOLTIP_CERTAIN_ODDS_TERM = "TOOLTIP_CERTAIN_ODDS";

		public const string TOOLTIP_LIKELY_ODDS_TERM = "TOOLTIP_LIKELY_ODDS";

		public const string TOOLTIP_EVEN_ODDS_TERM = "TOOLTIP_EVEN_ODDS";

		public const string TOOLTIP_UNLIKELY_ODDS_TERM = "TOOLTIP_UNLIKELY_ODDS";

		public const string TOOLTIP_IMPOSSIBLE_ODDS_TERM = "TOOLTIP_IMPOSSIBLE_ODDS";

		public const string TOOLTIP_SUCCESS_TERM = "TOOLTIP_SUCCESS";

		public const string TOOLTIP_FAILURE_TERM = "TOOLTIP_FAILURE";

		public const string TOOLTIP_FORCE_SUCCESS_TERM = "TOOLTIP_FORCE_SUCCESS";

		public const string TOOLTIP_FORCE_FAILURE_TERM = "TOOLTIP_FORCE_FAILURE";

		public const string TOOLTIP_LOCKED_TERM = "TOOLTIP_LOCKED";

		public const string TOOLTIP_PASSIVE_TERM = "TOOLTIP_PASSIVE";

		public const string TOOLTIP_LOCKED_EXPLANATION_TERM = "TOOLTIP_LOCKED_EXPLANATION";

		public const string TOOLTIP_DIFFICULT_TERM = "TOOLTIP_DIFFICULT";

		public const string TOOLTIP_VS_TERM = "TOOLTIP_VS";

		public const string TOOLTIP_ROLL_TERM = "TOOLTIP_ROLL";

		public const string TOOLTIP_DICE_TERM = "TOOLTIP_DICE";

		public const string TOOLTIP_MODIFIERS_TERM = "TOOLTIP_MODIFIERS";

		public const string TOOLTIP_CRITICAL_FAILURE_TERM = "TOOLTIP_CRITICAL_FAILURE";

		public const string TOOLTIP_CRITICAL_SUCCESS_TERM = "TOOLTIP_CRITICAL_SUCCESS";

		public const string TOOLTIP_TUTO_CHECK_WHITE_OPEN_TERM = "TOOLTIP_TUTO_CHECK_WHITE_OPEN";

		public const string TOOLTIP_TUTO_CHECK_RED_TERM = "TOOLTIP_TUTO_CHECK_RED";

		public const string TOOLTIP_EXPLAIN_PASSIVE_TERM = "TOOLTIP_EXPLAIN_PASSIVE";

		public const string TOOLTIP_EXPLAIN_WHITE_TERM = "TOOLTIP_EXPLAIN_WHITE";

		public const string TOOLTIP_EXPLAIN_RED_TERM = "TOOLTIP_EXPLAIN_RED";

		public const string TOOLTIP_YOU_HAVE_TERM = "TOOLTIP_YOU_HAVE";

		public const string TOOLTIP_COST_TERM = "TOOLTIP_COST";

		public const string TOOLTIP_HEAL_DAMAGE_ONE_TITLE_TERM = "TOOLTIP_HEAL_DAMAGE_ONE_TITLE";

		public const string TOOLTIP_HEAL_DAMAGE_ONE_DESC_TERM = "TOOLTIP_HEAL_DAMAGE_ONE_DESC";

		public const string TOOLTIP_HEAL_DAMAGE_ONE_SND_TERM = "TOOLTIP_HEAL_DAMAGE_ONE_SND";

		public const string TOOLTIP_HEAL_MORALE_ONE_TITLE_TERM = "TOOLTIP_HEAL_MORALE_ONE_TITLE";

		public const string TOOLTIP_HEAL_MORALE_ONE_DESC_TERM = "TOOLTIP_HEAL_MORALE_ONE_DESC";

		public const string TOOLTIP_HEAL_MORALE_ONE_SND_TERM = "TOOLTIP_HEAL_MORALE_ONE_SND";

		public const string TOOLTIP_TITLE_FORGET_REQ_TERM = "TOOLTIP_TITLE_FORGET_REQ";

		public const string TOOLTIP_DESCRIPTION_FORGET_NO_SKILL_POINTS_TERM = "TOOLTIP_DESCRIPTION_FORGET_NO_SKILL_POINTS";

		public const string TOOLTIP_TITLE_UNLOCK_REQ_TERM = "TOOLTIP_TITLE_UNLOCK_REQ";

		public const string TOOLTIP_DESCRIPTION_UNLOCK_SLOT_UNLOCKED_TERM = "TOOLTIP_DESCRIPTION_UNLOCK_SLOT_UNLOCKED";

		public const string TOOLTIP_TITLE_INITIALIZATION_REQ_TERM = "TOOLTIP_TITLE_INITIALIZATION_REQ";

		public const string TOOLTIP_DESCRIPTION_INITIALIZATION_NO_SLOT_TERM = "TOOLTIP_DESCRIPTION_INITIALIZATION_NO_SLOT";

		public const string THC_BASIC_VIEW_TITLE_TERM = "THC_BASIC_VIEW_TITLE";

		public const string THC_BASIC_VIEW_DESCRIPTION_TERM = "THC_BASIC_VIEW_DESCRIPTION";

		public const string THC_BASIC_SLOT_DESCRIPTION_TERM = "THC_BASIC_SLOT_DESCRIPTION";

		public const string THC_BASIC_UNLOCKABLE_SLOT_DESCRIPTION_TERM = "THC_BASIC_UNLOCKABLE_SLOT_DESCRIPTION";

		public const string THC_RESERACH_BONUS_NONE_TERM = "THC_RESERACH_BONUS_NONE";

		public const string THC_RESERACH_BONUS_PREFIX_TERM = "THC_RESERACH_BONUS_PREFIX";

		public const string THC_FIXED_BONUS_PREFIX_TERM = "THC_FIXED_BONUS_PREFIX";

		public const string THC_TOOLTIP_TITLE_PREFIX_TERM = "THC_TOOLTIP_TITLE_PREFIX";

		public const string COST_OPTION_ENTRY_PAID_TERM = "COST_OPTION_ENTRY_PAID";

		public const string COST_OPTION_ENTRY_COST_TERM = "COST_OPTION_ENTRY_COST";

		public const string COST_OPTION_ENTRY_LOCKED_TERM = "COST_OPTION_ENTRY_LOCKED";

		public const string CHECK_RESULT_SUCCESS_TERM = "CHECK_RESULT_SUCCESS";

		public const string CHECK_RESULT_FAILURE_TERM = "CHECK_RESULT_FAILURE";

		public const string CHECK_NODE_INVISIBLE_TERM = "CHECK_NODE_INVISIBLE";

		public const string CHECK_NODE_LOCKED_TERM = "CHECK_NODE_LOCKED";

		public const string ANNOTATION_LEVEL_UP_TERM = "ANNOTATION_LEVEL_UP";

		public const string ANNOTATION_TASK_COMPLETE_TERM = "ANNOTATION_TASK_COMPLETE";

		public const string ANNOTATION_SECRET_TASK_COMPLETE_TERM = "ANNOTATION_SECRET_TASK_COMPLETE";

		public const string ANNOTATION_NEW_TASK_TERM = "ANNOTATION_NEW_TASK";

		public const string ANNOTATION_MONEY_GAINED_TERM = "ANNOTATION_MONEY_GAINED";

		public const string ANNOTATION_MONEY_LOST_TERM = "ANNOTATION_MONEY_LOST";

		public const string ANNOTATION_THOUGHT_GAINED_TERM = "ANNOTATION_THOUGHT_GAINED";

		public const string ANNOTATION_ITEM_LOST_TERM = "ANNOTATION_ITEM_LOST";

		public const string ANNOTATION_ITEM_GAINED_TERM = "ANNOTATION_ITEM_GAINED";

		public const string ANNOTATION_SUBSTANCE_USED_TERM = "ANNOTATION_SUBSTANCE_USED";

		public const string ANNOTATION_XP_GAINED_SUFFIX_TERM = "ANNOTATION_XP_GAINED_SUFFIX";

		public const string TOOLTIP_HOVER_ITEM_READING_TERM = "TOOLTIP_HOVER_ITEM_READING";

		public const string TOOLTIP_HOVER_BOOK_READING_TERM = "TOOLTIP_HOVER_BOOK_READING";

		public const string TOOLTIP_INVENTORY_TITLE_TERM = "TOOLTIP_INVENTORY_TITLE";

		public const string TOOLTIP_INVENTORY_DESCRIPTION_TERM = "TOOLTIP_INVENTORY_DESCRIPTION";

		public const string INVENTORY_KEYS_TITLE_TERM = "INVENTORY_KEYS_TITLE";

		public const string INVENTORY_NO_KEYS_DESCRIPTION_TERM = "INVENTORY_NO_KEYS_DESCRIPTION";

		public const string PAWNSHOP_CONTAINS_ALTERNATION_TERM = "PAWNSHOP_CONTAINS_ALTERNATION";

		public const string MODIFIABLE_LABEL_DAMAGE_TERM = "MODIFIABLE_LABEL_DAMAGE";

		public const string SIGNATURE_SKILL_LABEL_TERM = "SIGNATURE_SKILL_LABEL";

		public const string DISPLAY_LABLE_ITEM_TERM = "DISPLAY_LABLE_ITEM";

		public const string DISPLAY_LABLE_THOUGHTS_TERM = "DISPLAY_LABLE_THOUGHTS";

		public const string SKILL_POINTS_LABEL_TERM = "SKILL_POINTS_LABEL";

		public const string RANK_FROM_CHARACTER_CREATION_LABEL_TERM = "RANK_FROM_CHARACHTER_CREATION_LABEL";

		public const string RANK_APPEND_CHARACTER_CREATION_LABEL_TERM = "RANK_APPEND_CHARACHTER_CREATION_LABEL";

		public const string BASE_ABILITY_LABEL_TERM = "BASE_ABILITY_LABEL";

		public const string CHARSHEET_ROLLED_THIS_EXPLANATION_TERM = "CHARSHEET_ROLLED_THIS_EXPLANATION";

		public const string DISPLAY_BASE_FOR_ABILITY_TERM = "DISPLAY_BASE_FOR_ABILITY";

		public const string SCREEN_PANEL_IMAGE_LOAD_TERM = "LOAD_SCREEN_PANEL_IMG";

		public const string SCREEN_PANEL_IMAGE_SAVE_TERM = "SAVE_SCREEN_PANEL_IMG";

		public const string HC_TOOLTIP_TITLE_TERM = "HC_TOOLTIP_TITLE";

		public const string HC_TOOLTIP_DESC_TERM = "HC_TOOLTIP_DESC";

		public const string HC_OPTION_TITLE_TERM = "HC_OPTION_TITLE";

		public const string HC_CONFIRMATION_ENABLING_TERM = "HC_CONFIRMATION_ENABLING";

		public const string HC_CONFIRMATION_DISABLING_TERM = "HC_CONFIRMATION_DISABLING";

		public const string INVENTORY_BULLETS_SLOT_TOOLTIP_DESCRIPTION_NO_TERM = "INVENTORY_BULLETS_SLOT_TOOLTIP_DESCRIPTION_NO";

		public const string INVENTORY_BULLETS_SLOT_TOOLTIP_DESCRIPTION_ONE_TERM = "INVENTORY_BULLETS_SLOT_TOOLTIP_DESCRIPTION_ONE";

		public const string INVENTORY_BULLETS_SLOT_TOOLTIP_DESCRIPTION_MANY_TERM = "INVENTORY_BULLETS_SLOT_TOOLTIP_DESCRIPTION_MANY";

		public const string INVENTORY_BULLETS_SLOT_TOOLTIP_TITLE_TERM = "INVENTORY_BULLETS_SLOT_TOOLTIP_TITLE";

		public const string FURIES_QUOTE_IMG_TERM = "FURIES_QUOTE_IMG";

		public const string CHARSHEET_SET_SIGNATURE_TITLE_TERM = "CHARSHEET_SET_SIGNATURE_TITLE";

		public const string CHARSHEET_SET_SIGNATURE_DESC_TERM = "CHARSHEET_SET_SIGNATURE_DESC";

		public const string JOURNAL_OFFICER_PROFILE_AGE_TERM = "JOURNAL_OFFICER_PROFILE_AGE";

		public const string DETECTIVE_NAME_TEQUILA_TERM = "DETECTIVE_NAME_TEQUILA";

		public const string DETECTIVE_NAME_INITIALS_TERM = "DETECTIVE_NAME_INITIALS";

		public const string DETECTIVE_NAME_HARRY_TERM = "DETECTIVE_NAME_HARRY";

		public const string DETECTIVE_NAME_HARRY_INITIALS_TERM = "DETECTIVE_NAME_HARRY_INITIALS";

		public const string DETECTIVE_NAME_FULLNAME_TERM = "DETECTIVE_NAME_FULLNAME";

		public const string DETECTIVE_NAME_RAPHAEL_TERM = "DETECTIVE_NAME_RAPHAEL";

		public const string KIM_GOODMORNING_BARK_TERM = "KIM_GOODMORNING_BARK";

		public const string KIM_REMOVING_PISSJACKET_BARK = "KIM_REMOVING_PISSJACKET_BARK";

		public const string REAL_CURRENCY_TERM = "REAL_CURRENCY";

		public const string JOURNAL_TASK_CANCELLED_TERM = "JOURNAL_TASK_CANCELLED";

		public const string INVENTORY_PLASTIC_BAG_BOTTLES_ONE_TERM = "INVENTORY_PLASTIC_BAG_BOTTLES_ONE";

		public const string INVENTORY_PLASTIC_BAG_BOTTLES_MORE_TERM = "INVENTORY_PLASTIC_BAG_BOTTLES_MORE";

		public const string SAVELOAD_NEW_SAVE_TERM = "SAVELOAD_NEW_SAVE";

		public const string SAVELOAD_INTERNAL_SAVE_TERM = "SAVELOAD_INTERNAL_SAVE";

		public const string QUIT_TO_DESKTOP_CONFIRMATION_TERM = "QUIT_TO_DESKTOP_CONFIRMATION";

		public const string QUIT_TO_MAIN_MENU_CONFIRMATION_TERM = "QUIT_TO_MAIN_MENU_CONFIRMATION";

		public const string CHARSHEET_BUTTON_LEVEL_UP_GREY_IMG_TERM = "CHARSHEET_BUTTON_LEVEL_UP_GREY_IMG";

		public const string SET_SKILL_TERM = "Skills/CHARSHEET_SKILL_TITLE";

		public const string ADJUST_ABILITIES_TERM = "Abilities/ABILITY_ADJUST_TITLE";

		public const string DIFFICULTY_TRIVIAL = "Difficulties/DIFFICULTY_TRIVIAL";

		public const string DIFFICULTY_EASY = "Difficulties/DIFFICULTY_EASY";

		public const string DIFFICULTY_MEDIUM = "Difficulties/DIFFICULTY_MEDIUM";

		public const string DIFFICULTY_CHALLENGING = "Difficulties/DIFFICULTY_CHALLENGING";

		public const string DIFFICULTY_FORMIDABLE = "Difficulties/DIFFICULTY_FORMIDABLE";

		public const string DIFFICULTY_LEGENDARY = "Difficulties/DIFFICULTY_LEGENDARY";

		public const string DIFFICULTY_HEROIC = "Difficulties/DIFFICULTY_HEROIC";

		public const string DIFFICULTY_GODLY = "Difficulties/DIFFICULTY_GODLY";

		public const string DIFFICULTY_IMPOSSIBRU = "Difficulties/DIFFICULTY_IMPOSSIBRU";

		public const string DIFFICULTY_NO_NAME = "Difficulties/DIFFICULTY_WITHOUT_NAME";

		public const string DELETE_CONFIRMATION_TERM = "Messages/CONFIRMATION_DELETE_SAVE";

		public const string DELETE_ALL_CONFIRMATION_TERM = "Messages/CONFIRMATION_DELETE_ALL_SAVE";

		public const string OVERWRITE_CONFIRMATION_TERM = "Messages/CONFIRMATION_OVERWRITE_SAVE";

		public const string CHARSHEET_FINALIZE_POINTS_TERM = "Messages/CHARSHEET_FINALIZE_POINTS";

		public const string CONFIRMATION_RESOLUTION_TERM = "Messages/CONFIRMATION_RESOLUTION_CHANGE";

		public const string CONFIRMATION_RESET_SETTINGS_TERM = "Messages/CONFIRMATION_RESET_SETTINGS";

		public const string NOTIFICATION_EXP_TERM = "Messages/NOTIFICATION_EXP";

		public const string NOTIFICATION_EXP_SUFFIX_TERM = "Messages/NOTIFICATION_EXP_SUFFIX";

		public const string NOTIFICATION_FINISHED_TASK_SUFFIX_TERM = "Messages/NOTIFICATION_FINISHED_TASK_SUFFIX";

		public const string NOTIFICATION_TUTORIAL_TERM = "Messages/NOTIFICATION_TUTORIAL_TAB";

		public const string NOTIFICATION_HEAL_YOURSELF_TERM = "Messages/NOTIFICATION_HEAL_YOURSELF";

		public const string THC_UNLOCK_SLOT_TERM = "Messages/THC_UNLOCK_SLOT";

		public const string THC_FORGET_THOUGHT_TERM = "Messages/THC_FORGET_THOUGHT";

		public const string INTERNAL_GAME_SAVE_ERROR_TERM = "Messages/ERROR_INTERNAL_SAVE";

		public const string EMPTY_NAME_GAME_SAVE_ERROR_TERM = "Messages/ERROR_EMPTY_NAME_SAVE";

		public const string NAME_EXISTS_GAME_SAVE_ERROR_TERM = "Messages/ERROR_NAME_EXISTS_SAVE";

		public const string SELECT_GAME_LOAD_ERROR_TERM = "Messages/ERROR_SELECT_LOAD";

		public const string SELECT_GAME_SAVE_ERROR_TERM = "Messages/ERROR_SELECT_SAVE";

		public const string LOAD_CONFIRMATION_TERM = "Messages/CONFIRMATION_LOAD";

		public const string CORRUPTED_SETTINGS_ERROR_TERM = "Messages/ERROR_SETTINGS_FILE_CORRUPTED";

		public const string ERROR_REPORT_TERM = "Messages/ERROR_REPORT";

		public const string MAX_SAVE_GAMES = "Messages/MAX_SAVE_GAMES";

		public const string NEW_GAME_WARNING_TERM = "NEW_GAME_WARNING";

		public const string GOODNIGHT_BARK_TERM = "KIM_GOODNIGHT_BARK";

		public const string BYE_BARK_TERM = "KIM_BYE_BARK";

		public const string NEVERMIND_BARK_TERM = "KIM_NEVERMIND_BARK";

		public const string TWITCH_CONNECTED = "CONNECTION ESTABLISHED";

		public const string TWITCH_CONNECTING_TO_SERVER = "CONNECTING TO SERVER";

		public const string TWITCH_ERROR_FAILED_CONNECT = "ERROR: FAILED TO CONNECT";

		public const string TWITCH_ERROR_INVALID_TOKEN = "ERROR: INVALID TWITCH TOKEN";

		public const string TWITCH_ERROR_UNKNOWN = "ERROR: UNKOWN";

		public const string NOTIFICATION_XP_DESCRIPTION_FORMAT = "+{0}{1}";

		public const string ABILITY_GRADE_LOCALIZATION_FORMAT = "Abilities/ABILITY_GRADE_{0}";

		public const string ATTRIBUTES_LOCALIZATION_FORMAT_TERM = "Abilities/ABILITY_NAME_{0}";

		public const string ABILITY_SHORT_LOCALIZATION_FORMAT_TERM = "Abilities/ABILITY_SHORT_{0}";

		public const string NAME_LOCALIZATION_FORMAT = "Archetypes/ARCHETYPE_NAME_{0}";

		public const string DESC_LOCALIZATION_FORMAT = "Archetypes/ARCHETYPE_DESC_{0}";

		public const string AREA_LOCALIZATION_NAME_FORMAT = "Area Names/{0}";

		public const string ACTORS_LOCALIZATION_FORMAT = "Actors/{0}/{1}";

		public const string THOUGHTS_LOCALIZATION_FORMAT = "Thoughts/{0}/{1}";

		public const string NEWSPAPERS_LOCALIZATION_FORMAT = "Newspapers/{0}/{1}";

		public const string TASKS_CATEGORY = "Conversation";

		public const string SUBTASKS_CATEGORY = "Substasks";

		public const string CONVERSATION_LOCALIZATION_FORMAT = "Conversation/{0}/{1}";

		public const string SKILL_LOCALIZATION_FORMAT_TERM = "Skills/SKILL_NAME_{0}";

		public const string OVERWRITE_QUESTION_FORMAT = "Messages/CONFIRMATION_OVERWRITE_SAVE";

		public const string WEEKDAY_TERM_FORMAT = "WEEKDAY_{0}";

		public const string EFFECT_THC_ORB_XP_FORMAT_TERM = "EFFECT_THC_ORB_XP";

		public const string EFFECT_TARGET_AGAINST_FORMAT_TERM = "EFFECT_TARGET_AGAINST";

		public const string EFFECT_ALL_WHITE_CHECKS_UNLOCKED_FORMAT_TERM = "EFFECT_ALL_WHITE_CHECKS_UNLOCKED_FORMAT";

		public const string EFFECT_MAX_LEARNING_CAP_RAISED_FORMAT_TERM = "EFFECT_MAX_LEARNING_CAP_RAISED";

		public const string EFFECT_MAX_LEARNING_CAP_ALL_RAISED_FORMAT_TERM = "EFFECT_MAX_LEARNING_CAP_ALL_RAISED";

		public const string EFFECT_MAX_LEARNING_CAP_ALL_SET_FORMAT_TERM = "EFFECT_MAX_LEARNING_CAP_ALL_SET";

		public const string EFFECT_MAX_LEARNING_CAP_FOR_RAISED_FORMAT_TERM = "EFFECT_MAX_LEARNING_CAP_FOR_RAISED";

		public const string EFFECT_SKILL_BONUS_WITHOUT_SHIRT_FORMAT_TERM = "EFFECT_SKILL_BONUS_WITHOUT_SHIRT";

		public const string EFFECT_SKILL_BONUS_WHEN_UNARMED_FORMAT_TERM = "EFFECT_SKILL_BONUS_WHEN_UNARMED";

		public const string EFFECT_PASSIVES_SUCCEED_FORMAT_TERM = "EFFECT_PASSIVES_SUCCEED";

		public const string EFFECT_PASSIVE_TARGET_MODIFIER_FORMAT_TERM = "EFFECT_PASSIVE_TARGET_MODIFIER";

		public const string EFFECT_XP_REWARD_FORMAT_TERM = "EFFECT_XP_REWARD";

		public const string REPUTATION_BONUS_FORMAT_TERM = "EFFECT_REPUTATION_BONUS";

		public const string EFFECT_MODIFY_CAMERA_MAX_ZOOM_LIMIT_FORMAT_TERM = "EFFECT_MODIFY_CAMERA_MAX_ZOOM_LIMIT";

		public const string TOOLTIP_TUTO_CHECK_WHITE_CLOSED_FORMAT_TERM = "TOOLTIP_TUTO_CHECK_WHITE_CLOSED";

		public const string TOOLTIP_HEAL_DAMAGE_ONE_EFF_FORMAT_TERM = "TOOLTIP_HEAL_DAMAGE_ONE_EFF";

		public const string TOOLTIP_HEAL_MORALE_ONE_EFF_FORMAT_TERM = "TOOLTIP_HEAL_MORALE_ONE_EFF";

		public const string COST_OPTION_FORMAT_TERM = "COST_OPTION_ENTRY";

		public const string ANNOTATION_SLEPT_HOURS_FORMAT_TERM = "ANNOTATION_SLEPT_HOURS";

		public const string ANNOTATION_ENDURANCE_HEALED_FORMAT_TERM = "ANNOTATION_ENDURANCE_HEALED";

		public const string ANNOTATION_VOLITION_REGAINED_FORMAT_TERM = "ANNOTATION_VOLITION_REGAINED";

		public const string ANNOTATION_GAINED_XP_FORMAT_TERM = "ANNOTATION_GAINED_XP";

		public const string ANNOTATION_XP_GAINED_PREFIX_FORMAT_TERM = "ANNOTATION_XP_GAINED_PREFIX";

		public const string ANNOTATION_QUICKTRAVEL_FISHING_VILLAGE_TERM = "ANNOTATION_QUICKTRAVEL_FISHING_VILLAGE";

		public const string ANNOTATION_QUICKTRAVEL_CHURCH_TERM = "ANNOTATION_QUICKTRAVEL_CHURCH";

		public const string TOOLTIP_HOVER_PRICE_FORMAT_TERM = "TOOLTIP_HOVER_PRICE";

		public const string TOOLTIP_HOVER_MINUTES_LEFT_FORMAT_TERM = "TOOLTIP_HOVER_MINUTES_LEFT";

		public const string TOOLTIP_HOVER_SUBSTANCE_USED_EFFECTS_FORMAT_TERM = "TOOLTIP_HOVER_SUBSTANCE_USED_EFFECTS";

		public const string TOOLTIP_HOVER_USES_LEFT_FORMAT_TERM = "TOOLTIP_HOVER_USES_LEFT";

		public const string TOOLTIP_HOVER_RESEARCH_EFFECTS_FORMAT_TERM = "TOOLTIP_HOVER_RESEARCH_EFFECTS";

		public const string TOOLTIP_HOVER_COMPLETION_EFFECTS_FORMAT_TERM = "TOOLTIP_HOVER_COMPLETION_EFFECTS";

		public const string CONFIRMATION_TIMER_TEXT_FORMAT_TEXT = "CONFIRMATION_TIMER_TEXT";

		public static string ADJUST_ABILITIES_FORMAT => null;

		public static string TOOLTIP_COST_FORMAT => null;

		public static string TOOLTIP_YOU_HAVE_FORMAT => null;

		public static string THC_TOOLTIP_RESEARCH_TIME_FORMAT => null;

		public static string THC_TOOLTIP_RESEARCH_TIME_REMAINING_MINUTES_FORMAT => null;

		public static string THC_TOOLTIP_EXP_FORMAT => null;

		public static string TASK_FILLED_FORMAT => null;

		public static string TASK_RESOLVED_FORMAT => null;

		public static string TASK_FORFEITED_FORMAT => null;

		public static string NOTIFICATION_FINISHED_TASK_FORMAT => null;

		public static string INVENTORY_TOOLTIP_INTERACT_FORMAT => null;

		public static string INVENTORY_TOOLTIP_USES_LEFT_FORMAT => null;

		public static string INVENTORY_TOOLTIP_PRICE_FORMAT => null;

		public static string COST_OPTION_ENTRY_FORMAT => null;

		public static string TIME_FORMAT => null;

		public static string PERCENTAGE_FORMAT => null;

		public static string SAVE_FORMAT => null;

		public static string THC_TOOLTIP_RESEARCH_TIME_REMAINING_FORMAT => null;

		public static string PAWN_MONEY_TOOLTIP_SPACE => null;

		public static string MONEY_FORMAT => null;

		public static string CHARSHEET_SKILLS_BONUSES_FORMAT => null;

		public static string CHARSHEET_SKILLS_BONUSES_KEY_FORMAT => null;

		public static string SIGNATURE_LOCALIZATION_FORMAT => null;
	}
}
