namespace Sunshine.Feld
{
	public enum FeldView
	{
		LOBBY = 0,
		TEST = 1,
		CLEAR = 2,
		GAME = 3,
		DIALOGUE = 4,
		DIALOGUETHOUGHTCABINET = 5,
		DIALOGUEJOURNAL = 6,
		DIALOGUECHARACTERSHEET = 7,
		INVENTORY = 8,
		INVENTORYDIALOGUE = 9,
		DIALOGUE_PAWN = 10,
		THOUGHTCABINET = 11,
		THOUGHTCABINETDIALOGUE = 12,
		JOURNAL = 13,
		CHARACTERSHEET = 14,
		NO_FELD = 15,
		CUTSCENEDIALOGUE = 16,
		PAUSE = 17,
		SETTINGS = 18,
		THOUGHTSPLASHSCREEN = 19,
		PHOTOMODE = 20
	}
}
