public enum SETTINGS_CATEGORY
{
	AUDIO = 0,
	BOOLEAN_WRITERS_TOOL = 1,
	TUTORIAL_TRACKER = 2,
	WRITERS_TOOL = 3,
	GRAPHICS = 4,
	LANGUAGE = 5,
	LOGGING_CATEGORY = 6,
	GAME_STATS = 7,
	COLLAGE_MODE = 8
}
