namespace Sunshine.Views
{
	public enum ViewType
	{
		LOBBY = 0,
		TEST = 1,
		CLEAR = 2,
		DIALOGUE = 3,
		INVENTORY = 4,
		INVENTORY_PAWN = 5,
		THOUGHTCABINET = 6,
		JOURNAL = 7,
		CHARACTERSHEET = 8,
		ARCHETYPE_SELECTION = 9,
		CHARACTER_CREATION_ADJUST_ABILITIES = 10,
		CHARACTER_CREATION_SET_SKILL = 11,
		CUTSCENE = 12,
		OPTIONS = 13,
		SAVE = 14,
		LOAD = 15,
		MAINMENU = 16,
		SPECIAL = 17,
		HELPOVERLAY = 18,
		THOUGHTSPLASHSCREEN = 19,
		COLLAGEMODE = 20
	}
}
